name: flutter_flavor_final
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_flavorizr: ^1.0.9
  flutter_test:
    sdk: flutter

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios: null
  flavors:
    dev:
      android:
        applicationId: "br.com.flutter.flavor.dev"
      app:
        name: "Flutter Flavor Dev"
      ios:
        bundleId: "br.com.flutter.flavor.dev"
    hom:
      android:
        applicationId: "br.com.flutter.flavor.hom"
      app:
        name: "Flutter Flavor Hom"
      ios:
        bundleId: "br.com.flutter.flavor.hom"
    prod:
      android:
        applicationId: "br.com.flutter.flavor"
      app:
        name: "Flutter Flavor"
      ios:
        bundleId: "br.com.flutter.flavor"
    qa:
      android:
        applicationId: "br.com.flutter.flavor.qa"
      app:
        name: "Flutter Flavor Qa"
      ios:
        bundleId: "br.com.flutter.flavor.qa"

flutter:

  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
